# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
        exclude: >
            (?x)^(
                .git/*|
                test_data/.*|
                cassandra-sstables/.*|
                alternator/.*|
                resources/.*|
            )$
    -   id: end-of-file-fixer
        exclude: >
            (?x)^(
                .git/*|
                test_data/.*|
                cassandra-sstables/.*|
                test-sstables/.*|
                alternator/.*
            )$
    -   id: check-yaml
        args:
        - --allow-multiple-documents
    -   id: check-added-large-files
    -   id: check-json
    -   id: detect-aws-credentials
    -   id: detect-private-key
        exclude: >
            (?x)^(
                resources/scylla.pem
            )$

-   repo: local
    hooks:
    -   id: autopep8
        name: autopep8
        entry: autopep8 -i -j 2 --max-line-length=120 --ignore=E226,E24,W50,W690,E402
        language: system
        types: [python]

    -   id: pylint
        name: pylint
        entry: pylint -j 2 -E
        files: >
            (?x)^(
                tools/.*|
                conftest.py|
                cassandra_batch_test.py|
                cdc_types_test.py|
                dtest_class.py|
                dtest_setup.py|
                deletion_test.py|
                bootstrap_test.py|
                migration_test.py|
                simple_driver_test.py|
                multidc_putget_test.py|
                consistent_bootstrap_test.py|
                replace_address_test.py|
                jmxmetrics_test.py|
                json_test.py|
                native_transport_ssl_test.py|
                read_amplification_test.py|
                cfid_test.py|
                cdc_ttl_test|
                cdc_test.py|
                cql_system_clients_test.py|
                sla_per_user_test.py|
                cql_tracing_addition_test.py|
                data_distribution_balance_test.py|
                internode_ssl_test.py|
                lwt_banking_load_test.py|
                lwt_schema_modification_test.py|
                super_counter_test.py|
                thrift_tests.py|
                lwt_test.py|
                lwt_random_test.py|
                lwt_destructive_ddl_test.py|
                auth_test.py|
                paging_test.py|
                snapshot_test|
                udtencoding_test.py|
                clustering_key_filter_test.py|
                ttl_test.py|
                audit_test.py|
                user_types_test.py|
                user_functions_test.py|
                in_memory_test.py|
                hintedhandoff_test.py|
                hintedhandoff_additional_test.py|
                materialized_views_test.py|
                toppartitions_test.py|
                resharding_test.py|
                replication_test.py|
                heat_weighted_load_balancing_test.py|
                upgrade_test.py|
                consistency_test.py|
                secondary_indexes_test.py|
                like_operator_test.py|
                paxos_tests.py|
                sstableutil_test.py|
                sstablesplit_test.py|
                jmx_test.py|
                schema_test.py|
                listsnapshots_test.py|
                write_failures_test.py|
                topology_test.py|
                database_metrics_test.py|
                sstableloader_test.py|
                pushed_notifications_test.py|
                persistence_test.py|
                cql_tracing_test.py|
                compaction_test.py |
                deprecated_repair_test.py|
                putget_test.py|
                nodetool_test.py|
                updateable_config_test.py|
                manager_backup_tests.py|
                manager_general_tests.py|
                manager_health_check_tests.py|
                manager_repair_tests.py|
                manager_task_tests.py|
                rolling_upgrade_test.py|
                simple_cluster_driver_test.py|
                incremental_repair_test.py|
                simple_boot_shutdown_test.py|
                mixed_version_test.py|
                alternator_tests.py|
                wide_rows_test.py|
                batch_test.py|
                cql_cast_test.py|
                concurrent_schema_changes_test.py|
                sstable_generation_loading_test.py|
                schema_management_test.py|
                compaction_additional_test.py|
                compression_test.py|
                simple_no_driver_test.py|
                sstabledump_test.py|
                cqlsh_tests/.*|
                delete_insert_test.py|
                scyllatop_test.py|
                counter_tests.py|
                auth_roles_test.py|
                configuration_test.py|
                cql_group_functions_tests.py|
                scrub_test.py|
                compact_storage_tests.py|
                largecolumn_test.py|
                cql_tests.py|
                upgrade_internal_auth_test.py|
                partitioner_tests.py|
                rebuild_test.py|
                ics_compaction_test.py|
                offline_tools_test.py|
                update_cluster_layout_tests.py|
                pytest_cql_additional_tests.py|
                repair_additional_test.py|
                upgrade_tests/.*|
                cdc_snapshot_operation_test.py|
                encryption_at_rest_test.py|
                rest_api_tests.py|
                error_example_test.py|
                limits_test.py|
                metadata_tests.py|
                ldap_test.py|
                repair_test.py|
                paging_additional_test.py|
                nodetool_additional_test.py|
                global_row_key_cache_test.py|
                cql_additional_tests.py
            )$
        language: system
        types: [python]
