import os
import logging
import distutils.dir_util

import pytest

from dtest_class import Tester

logger = logging.getLogger(__name__)


@pytest.mark.dtest_full
class TestPartitioner(Tester):

    def run_cluster(self, partitioner_name, data_dir, deprecated=False):
        # The test starts Scylla using work directories created by Cassandra.
        # This is not a supported scenario; it's like upgrading Scylla from a
        # very old version, when the documentation only allows upgrading
        # between consecutive versions or compatible OSS/enterprise versions.
        # In this scenario, Scylla may try to insert CDC cluster metadata into
        # a table which is no longer created in new Scylla versions. This will
        # cause an ERROR to appear in the logs (the cluster will boot and
        # function, just without CDC). Ignore this pattern so the test can
        # pass.
        self.ignore_log_patterns.append('expected system_distributed.cdc_generation_descriptions to exist')

        cluster = self.cluster
        if deprecated:
            cluster.set_configuration_options(values={'enable_deprecated_partitioners': True})
        cluster.set_partitioner(partitioner_name)

        logger.debug("Populate 3 Nodes")
        c = cluster.populate(3)

        node1 = cluster.nodelist()[0]
        node2 = cluster.nodelist()[1]
        node3 = cluster.nodelist()[2]

        logger.debug("Get dst data directory")
        dst1 = os.path.join(node1.get_path(), 'data')
        dst2 = os.path.join(node2.get_path(), 'data')
        dst3 = os.path.join(node3.get_path(), 'data')
        logger.debug("dst1=%s, dst2=%s, dst2=%s" % (dst1, dst2, dst3))

        logger.debug("Get src data directory")
        src1 = os.path.join("test_data", data_dir, "1", "data")
        src2 = os.path.join("test_data", data_dir, "2", "data")
        src3 = os.path.join("test_data", data_dir, "3", "data")
        logger.debug("src1=%s, src2=%s, src3=%s" % (src1, src2, src3))

        logger.debug("Copy data generated by Cassandra")
        distutils.dir_util.copy_tree(src1, dst1)
        distutils.dir_util.copy_tree(src2, dst2)
        distutils.dir_util.copy_tree(src3, dst3)

        logger.debug("Start 3 Nodes")

        c.start(wait_for_binary_proto=True, wait_other_notice=True)

        session = self.patient_cql_connection(node1)

        result = list(session.execute("SELECT * FROM ks2.tb"))

        assert len(result) == 30

    @pytest.mark.next_gating
    @pytest.mark.dtest_debug
    @pytest.mark.gossip_only
    def test_murmur3_partitioner(self):
        self.run_cluster("org.apache.cassandra.dht.Murmur3Partitioner",
                         "cassandra.3.nodes.30.rows.256.murmur3.partitioner")
