import threading
import time
from datetime import datetime
import os
import distutils.dir_util

from cassandra import Unavailable, ConsistencyLevel, WriteTimeout, OperationTimedOut
from cassandra.policies import FallthroughRetryPolicy
from cassandra.query import SimpleStatement
from cassandra.cluster import NoHostAvailable
from ccmlib.node import NodeError

from dtest import Tester, debug
from tools import insert_c1c2, query_c1c2, new_node


class TestPartitioner(Tester):

    def run_cluster(self, partitioner_name, data_dir):
        cluster = self.cluster
        cluster.set_partitioner(partitioner_name)

        debug("Populate 3 Nodes")
        c = cluster.populate(3)

        node1 = cluster.nodelist()[0]
        node2 = cluster.nodelist()[1]
        node3 = cluster.nodelist()[2]

        debug("Get dst data directory")
        dst1 = os.path.join(node1.get_path(), 'data')
        dst2 = os.path.join(node2.get_path(), 'data')
        dst3 = os.path.join(node3.get_path(), 'data')
        debug("dst1=%s, dst2=%s, dst2=%s" % (dst1, dst2, dst3))

        debug("Get src data directory")
        src1 = os.path.join("test_data", data_dir, "1", "data")
        src2 = os.path.join("test_data", data_dir, "2", "data")
        src3 = os.path.join("test_data", data_dir, "3", "data")
        debug("src1=%s, src2=%s, src3=%s" % (src1, src2, src3))

        debug("Copy data generated by Cassandra")
        distutils.dir_util.copy_tree(src1, dst1)
        distutils.dir_util.copy_tree(src2, dst2)
        distutils.dir_util.copy_tree(src3, dst3)

        debug("Start 3 Nodes")

        c.start()

        session = self.patient_cql_connection(node1)

        result = session.execute("SELECT * FROM ks2.tb")

        self.assertEqual(len(result), 30, len(result))

    def random_partitioner_test(self):
        self.run_cluster("org.apache.cassandra.dht.RandomPartitioner", "cassandra.3.nodes.30.rows.256.random.partitioner")

    def byteordered_partitioner_test(self):
        self.run_cluster("org.apache.cassandra.dht.ByteOrderedPartitioner", "cassandra.3.nodes.30.rows.256.byteordered.partitioner")

    def murmur3_partitioner_test(self):
        self.run_cluster("org.apache.cassandra.dht.Murmur3Partitioner", "cassandra.3.nodes.30.rows.256.murmur3.partitioner")
