[pytest]
python_files = test_*.py *_test.py *_tests.py
log_cli=true
log_cli_level = ERROR
log_level = DEBUG
log_format = %(asctime)s,%(msecs)03d %(name)-15s %(levelname)-5s %(filename)-15s:%(lineno)-4d | %(message)s
log_file_format = %(asctime)s,%(msecs)03d %(process)-7d %(name)-30s %(levelname)-8s %(filename)-20s:%(lineno)-4d | %(test_name)s: %(message)s
log_file= logs/dtest.log

markers =
    next_gating: test that are used of gating tests
    dtest_full: the full dtest suite, we run daily on master (and release branches)
    dtest_debug: test selection for debug version
    dtest_smoke: few sanity check test we run in next before the rest of the suite `next_gating`
    not_debug:
    single_node: test that are mark like this, should be using only one node, and should boot much quicker
