[pytest]
addopts = -p no:flaky
python_files = test_*.py *_test.py *_tests.py
log_cli=true
log_cli_level = ERROR
log_level = DEBUG
log_format = %(asctime)s,%(msecs)03d %(name)-15s %(levelname)-5s %(filename)-15s:%(lineno)-4d | %(message)s
log_file_format = %(asctime)s,%(msecs)03d %(process)-7d %(name)-30s %(levelname)-8s %(filename)-20s:%(lineno)-4d | %(test_name)s: %(message)s
log_file= logs/dtest.log
timeout = 2700

render_collapsed = True

markers =
    next_gating: test that are used of gating tests
    scylla_cdc: test agains CDC functionality (https://docs.scylladb.com/using-scylla/cdc/)
    dtest_full: the full dtest suite, we run daily on master (and release branches)
    dtest_debug: test selection for debug version
    dtest_smoke: few sanity check test we run in next before the rest of the suite `next_gating`
    dtest_long: that that are taking more then 30min
    single_node: test that are mark like this, should be using only one node, and should boot much quicker
    no_vnodes: test doesn't support running when vnode enable
    vnode: test that can run only when vnodes are enabled
    dtest_heavy: tests that needs more then 4 cpus for working
    vnodes: test have to have vnode enable
    require: test should be skipped until issue is close/fixed
    scylla_mode: used to skip test base on their scylla mode ex. `@pytest.mark.scylla_mode('!debug')`
    resource_intensive: resource intensive (inherited from cassandra-dtest, we didn't have a clear definition of what it means)
    since: used by old cassandra tests (inherited from cassandra-dtest, we are using branch instead and backporting fixes into them)
    scylla_manager: Tests for scylla manager
    dtest_enterprise: The tests that are relevant only for Scylla enterprise releases
