#!/bin/bash
#
# Usage:
#
# scripts/setup-virtualenv --virtualenv-root=PATH --python=PATH

CASSANDRA_DRIVER_VERSION='3.7.1'
THRIFT_VERSION='0.9.3'

PROGRAM=$(basename $0)

usage() {
    echo "usage: $PROGRAM --virtualenv-root=PATH --python=PATH"
}

set -e

for i in "$@"
do
case $i in
    -v=*|--virtualenv-root*)
    VIRTUALENV_ROOT="${i#*=}"
    shift
    ;;
    -p=*|--python*)
    PYTHON="${i#*=}"
    shift
    ;;
    *)
    echo "error: unknown command line option: $i"
    usage
    exit 1
    ;;
esac
done

if [ -z $VIRTUALENV_ROOT ]; then
    echo "error: no virtualenv root defined, use the --virtualenv-root option to specify that"
    usage
    exit 1
fi

echo "VIRTUALENV_ROOT = $VIRTUALENV_ROOT"
echo "CASSANDRA_DRIVER_VERSION = $CASSANDRA_DRIVER_VERSION"
echo "THRIFT_VERSION = $THRIFT_VERSION"
echo "PYTHON = $PYTHON"

#
# Setup virtualenv:
#
if [ -n "$PYTHON" ]; then
    VIRTUALENV_OPTS="-p $PYTHON"
fi

rm -rf $VIRTUALENV_ROOT
virtualenv $VIRTUALENV_OPTS $VIRTUALENV_ROOT
source $VIRTUALENV_ROOT/bin/activate
easy_install -U setuptools==28.8.0
pip install cassandra-driver==$CASSANDRA_DRIVER_VERSION
pip install thrift==$THRIFT_VERSION
pip install nose
pip install psutil
pip install pyyaml
pip install enum34
pip install nose_xunitmp
pip install python-dateutil
