#!/bin/bash
#
# Usage:
#
# scripts/setup-virtualenv --virtualenv-root=PATH

CASSANDRA_DRIVER_VERSION='3.7.1'

PROGRAM=$(basename $0)

usage() {
    echo "usage: $PROGRAM --virtualenv-root=PATH"
}

set -e

for i in "$@"
do
case $i in
    -v=*|--virtualenv-root*)
    VIRTUALENV_ROOT="${i#*=}"
    shift
    ;;
    *)
    echo "error: unknown command line option: $i"
    usage
    exit 1
    ;;
esac
done

if [ -z $VIRTUALENV_ROOT ]; then
    echo "error: no virtualenv root defined, use the --virtualenv-root option to specify that"
    usage
    exit 1
fi

echo "VIRTUALENV_ROOT = $VIRTUALENV_ROOT"
echo "CASSANDRA_DRIVER_VERSION = $CASSANDRA_DRIVER_VERSION"

#
# Setup virtualenv:
#
rm -rf $VIRTUALENV_ROOT
virtualenv $VIRTUALENV_ROOT
source $VIRTUALENV_ROOT/bin/activate
easy_install -U setuptools
pip install cassandra-driver==$CASSANDRA_DRIVER_VERSION
pip install thrift
pip install nose
pip install psutil
pip install pyyaml
